export const ADD_TO_DASHBOARD_REQUEST = "ADD_TO_DASHBOARD_REQUEST";
export const ADD_TO_DASHBOARD_SUCCESS = "ADD_TO_DASHBOARD_SUCCESS";
export const ADD_TO_DASHBOARD_FAILURE = "ADD_TO_DASHBOARD_FAILURE";

export const GET_DASHBOARD_DATA_REQUEST = "GET_DASHBOARD_DATA_REQUEST";
export const GET_DASHBOARD_DATA_SUCCESS = "GET_DASHBOARD_DATA_SUCCESS";
export const GET_DASHBOARD_DATA_FAILURE = "GET_DASHBOARD_DATA_FAILURE";

export const QUIZ_SETUP_REQUEST = "QUIZ_SETUP_REQUEST";
export const QUIZ_SETUP_SUCCESS = "QUIZ_SETUP_SUCCESS";
export const QUIZ_SETUP_FAILURE = "QUIZ_SETUP_FAILURE";

export const QUIZ_OPTION_REQUEST = "QUIZ_OPTION_REQUEST";
export const QUIZ_OPTION_SUCCESS = "QUIZ_OPTION_SUCCESS";
export const QUIZ_OPTION_FAILURE = "QUIZ_OPTION_FAILURE";
